# Generated by Django 5.0 on 2024-06-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mybackend", "0003_alter_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_category",
            field=models.CharField(
                choices=[
                    ("Esewa", "esewa"),
                    ("Khalti", "khalti"),
                    ("Fonepay", "fonepay"),
                    ("Imepay", "Imepay"),
                    ("Bank", "bank"),
                    ("Cash", "cash"),
                ],
                max_length=100,
            ),
        ),
    ]
